Modified ingress config (#130)
data-prep-kit/data-prep-kit pull request #156
Opened 2024-05-21 11:36 UTC by D-Sai-Venkatesh

## Why are these changes needed?
Added a new ingress controller to enable both KFP and Minio to take separate default URL paths.

## Related issue number (if any).
130

2024-05-21 17:26 UTC, blublinsky approved these changes

2024-05-21 18:40 UTC, roytman commented on kind/README.md
> +Install [Ingress NGNIX](https://kind.sigs.k8s.io/docs/user/ingress/#ingress-nginx) for KFP and RAY and wait for it to be ready:
`for KFP and Ray/MinIO`

2024-05-21 19:01 UTC, roytman reviewed
you need to update the following files too:
```
README.md:25:> **NOTE**: Additionally, ensure that nothing is running on port 8080, which is used by the Kind cluster ingress.
README.md:36:8080 is available, creation of the cluster, installing required software (NGNIX, KubeRay and KFP), creating
README.md:124:Open the Kubeflow Pipelines UI at  http://localhost:8080/
hack/tools/kind_management.sh:33:  if lsof -Pi :8080 -sTCP:LISTEN -t >/dev/null ; then
hack/tools/kind_management.sh:34:      echo "port 8080 is in use, please clear the port and try again"
```

2024-05-21 19:01 UTC, roytman commented on kind/hack/nginx_deploy_minio.yaml
> +apiVersion: v1
Do we need to deploy the second ingress in a separate namespace? can both be deployed in the same namespace and use the same SA and RBAC roles?

2024-05-21 19:01 UTC, roytman commented on kind/hack/tools/install_nginx.sh
> +		echo "NGINX Deployment unsuccessful. Not all pods running"
can you change the message to something like:
""NGINX MinIO deployment unsuccessful. Not all pods running"

2024-05-21 19:01 UTC, roytman commented on kind/hack/tools/install_nginx.sh
> +	kubectl apply -f "$NGINX_MINIO_INSTALLATION_FILE"
kubectl **delete** -f "$NGINX_MINIO_INSTALLATION_FILE"

2024-05-21 19:04 UTC, roytman commented on kind/hack/tools/install_nginx.sh
>  MAX_RETRIES="${MAX_RETRIES:-10}"
can you change the default at Line 5 to 60

2024-05-21 19:04 UTC, roytman requested changes
@D-Sai-Venkatesh thank you for your PR, several comments

2024-05-21 19:07 UTC, roytman commented on kind/hack/populate_minio.sh
Please rebase your PR, the `mc cp` path is wrong

2024-05-28 11:20 UTC, roytman approved these changes
LGTM

2024-05-28 12:38 UTC, revit13 approved these changes

2024-05-28 13:01 UTC, merged