License and Copyright header removal
data-prep-kit/data-prep-kit pull request #239
Opened 2024-06-07 05:36 UTC by ykalathiya

Here, We have used scancode.api to detect the license and copyright.

## Why are these changes needed?
This help to remove license and copyright from any language of code.

## Related issue number (if any).

2024-06-07 15:34 UTC, daw3rd commented
Please run `make conventions` in your transforms/[ray,python] directories

2024-06-07 15:35 UTC, daw3rd commented
And please split the ray tree into ray and python runtimes.  See filter and noop projects for examples.

2024-06-07 15:36 UTC, daw3rd requested changes
Per earlier comments, split the ray dir into ray and python-only runtimes.
Also, after doing that, run `make conventions` in each of the python and ray directories.

2024-06-08 16:41 UTC, daw3rd commented
https://github.com/IBM/data-prep-kit/tree/dev/transforms#transform-project-conventions will be helpful on splitting ray/python.  also, generally you may want to copy the Makefile and Dockerfile from the universal/filter/[ray,python] directories and use as templates.  Also note the various readmes.

2024-06-11 01:29 UTC, daw3rd requested changes
Per the build failure, you need to create a test directory with some tests.  However,  you might wait to do that until you split the ray dir into ray and python.  See one of the other transforms like universal/filter that shows how this can be done.

2024-06-18 05:16 UTC, ykalathiya commented
@daw3rd @Param-S @Bytes-Explorer I updated the PR. Please review it.

2024-06-18 05:49 UTC, shivdeep-singh-ibm commented
@ykalathiya You should [update your name and email  in .gitconfig](https://linuxize.com/post/how-to-configure-git-username-and-email/#setting-global-git-username-and-email)and ad sign off to your commits `git commit -s -m <some message>`. Then you will not get `DCO` Failure.

2024-06-18 07:29 UTC, Param-S commented on transforms/code/license_copyright_removal/python/Dockerfile
> +#COPY requirements.txt requirements.txt
@ykalathiya i think, this needs to be uncommented. I see a docker build failure due to scancode module missing...
https://github.com/IBM/data-prep-kit/actions/runs/9560117498/job/26352464226?pr=239

2024-06-18 11:32 UTC, ykalathiya reviewed
Changed Docker file.

2024-06-21 07:45 UTC, ykalathiya commented
I'm closing this PR due to commit sign off failures. I have created new PR. #315

2024-06-21 07:45 UTC, closed without merging