Fix readme repo level tf
data-prep-kit/data-prep-kit pull request #439
Opened 2024-07-23 15:57 UTC by shivdeep-singh-ibm

## Why are these changes needed?

## Related issue number (if any).

2024-07-23 17:40 UTC, daw3rd requested changes

2024-07-23 17:40 UTC, daw3rd commented on transforms/code/repo_level_ordering/ray/README.md
> +
Can you add the short section on running as an image. For example, https://github.com/IBM/data-prep-kit/blob/dev/transforms/universal/noop/ray/README.md#transforming-data-using-the-transform-image

2024-07-23 17:49 UTC, Param-S requested changes

2024-07-23 17:49 UTC, Param-S commented on transforms/code/repo_level_ordering/ray/README.md
> +This transform ccan group the data by `repo_name` and apply additional transformations
`ccan` - typo

2024-07-23 17:49 UTC, Param-S commented on transforms/code/repo_level_ordering/ray/README.md
> +Recommended `repo_lvl_store_type` for cluster is 'ray'. We need to dedicate some ray actors specially for
can we describe more about this option `repo_lvl_store_type` in section `Configuration and command line Options`. 

If we include details which describe the list of supported values and its usage/application.

2024-07-23 17:49 UTC, Param-S commented on transforms/code/repo_level_ordering/ray/README.md
> +use 80 for computation and 10 for store and let 10 remain free.
What is the reason for leaving 10 actors free? Whats the logic behind this example actors allocation? (based on the input data volume or data/repo distribution)?

2024-07-24 15:41 UTC, daw3rd commented
Can you also add this transform to the table in the top level README.md

2024-07-30 13:49 UTC, shivdeep-singh-ibm commented
readme changes as part in https://github.com/IBM/data-prep-kit/pull/434

2024-07-30 13:49 UTC, closed without merging