Pii transform
data-prep-kit/data-prep-kit pull request #468
Opened 2024-07-31 14:29 UTC by SowmyaLR

## Why are these changes needed?
Included a new transform for pii redaction

## Related issue number (if any).

https://github.com/IBM/data-prep-kit/issues/62

2024-07-31 18:33 UTC, santoshborse requested changes

2024-07-31 18:33 UTC, santoshborse commented on transforms/universal/pii_redactor/python/src/pii_redactor_transform.py
> +                table = table.add_column(0, "new_contents", [column_data])
you can rewrite this block to make it more readable
```
if self.doc_contents_key in table.column_names:
    column_data = pa.array(table[self.doc_contents_key].to_pandas().apply(self._redact_pii))
    table = table.add_column(0, "new_contents", [column_data])
```

2024-07-31 18:36 UTC, santoshborse commented on transforms/universal/pii_redactor/python/src/pii_redactor_transform.py
> +                table = table.add_column(0, "new_contents", [column_data])
in fact you don't even need `if` line as you have ready have used `TransformUtils.validate_columns` make sure column `self.doc_contents_key` is in table

2024-08-01 07:01 UTC, SowmyaLR commented
@santoshborse seems  conflict issues. Will fix it and raise a clean PR.

2024-08-01 07:01 UTC, closed without merging