Add new notebook
data-prep-kit/data-prep-kit pull request #473
Opened 2024-08-05 18:16 UTC by shivdeep-singh-ibm

## Why are these changes needed?

## Related issue number (if any).

2024-08-09 06:13 UTC, Bytes-Explorer reviewed
Descriptions are missing, need to be added.

2024-08-09 06:20 UTC, Bytes-Explorer commented
Parameters in the first cell should be hidden. Only user facing params should be retained and adequate description should be added.

2024-08-09 06:22 UTC, Bytes-Explorer reviewed
Please make them as a single pip install that Maroun is building.

2024-08-09 06:29 UTC, Bytes-Explorer commented
All cells should have a markdown format on what are the parameters, how should an end user use them etc, See https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.FeatureHasher.html#sklearn.feature_extraction.FeatureHasher for inspiration.

2024-08-09 06:30 UTC, Bytes-Explorer commented
Change ray_params to an easy to use name for a data scientist

2024-08-12 15:46 UTC, santoshborse requested changes, later dismissed
`Tokenization` spelled wrong in multiple places

2024-08-12 15:46 UTC, santoshborse commented on examples/notebooks/code/transform_requirements.txt
> +# Tokenisation
spell check - should be `Tokenization`

2024-08-12 15:46 UTC, santoshborse commented on examples/notebooks/code/sample-notebook.ipynb
> +    "- Tokenisation\n",
spell check - should be `Tokenization`

2024-08-12 15:46 UTC, santoshborse commented on examples/notebooks/code/sample-notebook.ipynb
> +    "## Tokenisation"
spell check - should be `Tokenization`

2024-08-22 21:44 UTC, touma-I approved these changes

2024-08-22 21:46 UTC, touma-I commented
This iteration meets current needs. Expect more iterations in new PR

2024-08-22 21:46 UTC, merged