pipeline transform
data-prep-kit/data-prep-kit pull request #602
Opened 2024-09-19 20:05 UTC by blublinsky

## Why are these changes needed?

Implementation of pipeline transform similar to Sklearn approach

## Related issue number (if any).

https://github.com/IBM/data-prep-kit/issues/374
https://github.com/IBM/data-prep-kit/issues/544

2024-09-23 05:55 UTC, roytman commented
@daw3rd , I looked over this PR and it is OK for me, but leave it for your final verdict.

2024-09-23 12:32 UTC, daw3rd requested changes
Can we run a pipeline outside of the runtime/launcher?  If so, I'd like to see a test or other example of how this is done?  If not, we need it.

2024-09-23 14:01 UTC, blublinsky commented
> Can we run a pipeline outside of the runtime/launcher? If so, I'd like to see a test or other example of how this is done? If not, we need it.

For running a pipeline outside a runtime we have kfp. We can not pass values in memory outside of runtime

2024-09-23 14:20 UTC, daw3rd commented
> > Can we run a pipeline outside of the runtime/launcher? If so, I'd like to see a test or other example of how this is done? If not, we need it.
> 
> For running a pipeline outside a runtime we have kfp. We can not pass values in memory outside of runtime

This is a problem and does not meet requirements defined in the issue. https://github.com/IBM/data-prep-kit/issues/374#issuecomment-2353447356

2024-09-23 14:23 UTC, blublinsky commented
> > > Can we run a pipeline outside of the runtime/launcher? If so, I'd like to see a test or other example of how this is done? If not, we need it.
> > 
> > 
> > For running a pipeline outside a runtime we have kfp. We can not pass values in memory outside of runtime
> 
> This is a problem and does not meet requirements defined in the issue. [#374 (comment)](https://github.com/IBM/data-prep-kit/issues/374#issuecomment-2353447356)

The requirement does not specify the ability to run across runtimes. Besides, where is this requirement coming from?

2025-06-26 15:06 UTC, swith005 commented
added as transform chain in #1329

2025-06-26 15:06 UTC, closed without merging