Higher order syntactic and semantic profiler transforms
data-prep-kit/data-prep-kit pull request #653
Opened 2024-10-01 18:48 UTC by aishwariyachakraborty

## Why are these changes needed?
This PR implements the higher order syntactic and semantic profiler transforms as a downstream application of the UBSR transform.

## Related issue number (if any).

2024-10-02 15:20 UTC, daw3rd requested changes

2024-10-02 15:20 UTC, daw3rd commented on transforms/code/higher_order_syntactic_profiler/python/README.md
> +  --hosp_metrics_list HOSP_METRICS_LIST
Need to be more specific about what are the allowed options and the defaults.  Following the format used [here](https://github.com/IBM/data-prep-kit/tree/dev/transforms/language/pdf2parquet/python#ingest-pdf-to-parquet) would be helpful.

2024-10-02 15:20 UTC, daw3rd commented on transforms/code/semantic_profiler/python/src/sp_transform.py
> +        self.ikb_file = config.get("ikb_file", "../src/ikb/ikb_model.csv")
Can you confirm that the wheel built for this transform 1) includes the csv files and 2) that they can be accessed from within the wheel file?  If not, these defaults would only seem to work within the repo, but we need defaults that work when the wheel is used.

2024-10-03 11:37 UTC, aishwariyachakraborty commented on transforms/code/semantic_profiler/python/src/sp_transform.py
> +        self.ikb_file = config.get("ikb_file", "../src/ikb/ikb_model.csv")
I have made changes to the pyproject.toml files. The files are present and can be accessed.

2024-10-04 12:04 UTC, daw3rd requested changes

2024-10-04 12:04 UTC, daw3rd commented on .github/workflows/test-code-semantic_profiler.yml
please merge your branch with dev and regenerate this file.

2024-10-04 12:04 UTC, daw3rd commented on .github/workflows/test-code-higher_order_syntactic_profiler.yml
please merge your branch with dev and regenerate this file.

2024-10-04 12:04 UTC, daw3rd commented on transforms/code/higher_order_syntactic_profiler/Makefile
> +workflow-venv:
Please match these rules with the latest from dev. For example, https://github.com/IBM/data-prep-kit/blob/2a86cec4ddf0bbb0d43c6eb403d4b6c08a7c6a19/transforms/universal/noop/Makefile#L56

2024-10-04 12:04 UTC, daw3rd commented on transforms/code/higher_order_syntactic_profiler/python/pyproject.toml
> +    { name = "David Wood", email = "dawood@us.ibm.com" },
Please provide correct names here.

2024-10-04 12:04 UTC, daw3rd commented on transforms/code/higher_order_syntactic_profiler/ray/pyproject.toml
> +    { name = "David Wood", email = "dawood@us.ibm.com" },
Please provide correct names here.

2024-10-04 12:04 UTC, daw3rd commented on transforms/code/semantic_profiler/python/pyproject.toml
> +    { name = "David Wood", email = "dawood@us.ibm.com" },
Please provide correct names here.

2024-10-04 12:04 UTC, daw3rd commented on transforms/code/semantic_profiler/ray/pyproject.toml
> +    { name = "David Wood", email = "dawood@us.ibm.com" },
Please provide correct names here.

2024-10-04 12:04 UTC, daw3rd commented on transforms/code/semantic_profiler/Makefile
> +.PHONY: workflow-venv
Please match these rules with the latest from dev. For example, https://github.com/IBM/data-prep-kit/blob/2a86cec4ddf0bbb0d43c6eb403d4b6c08a7c6a19/transforms/universal/noop/Makefile#L56

2024-10-04 12:20 UTC, aishwariyachakraborty commented on transforms/code/higher_order_syntactic_profiler/python/pyproject.toml
> +    { name = "David Wood", email = "dawood@us.ibm.com" },
done

2024-10-04 13:00 UTC, aishwariyachakraborty commented
I have made all the changes you have requested. I do not have an option to merge yet. It shows : Merging is blocked
Merging can be performed automatically once the requested changes are addressed.

2024-10-04 13:13 UTC, aishwariyachakraborty commented on .github/workflows/test-code-semantic_profiler.yml
I have made all the changes you have requested. I do not have an option to merge yet. It shows : Merging is blocked
Merging can be performed automatically once the requested changes are addressed.

2024-10-04 13:30 UTC, daw3rd requested changes

2024-10-04 13:30 UTC, daw3rd commented on transforms/code/higher_order_syntactic_profiler/python/README.md
> +| `HOSP_METRICS_LIST`         | `CCR`        | Metrics to be calculated for profiling. Multiple metrics can be entered separated by space. Only valid metric is `CCR` as of now. |
I believe the key needs to be in lower case, per the transform implementation.  And, the transform seems to look for `metrics` not `metrics_list` and definitely not `hosp_metrics_list`.

2024-10-04 13:30 UTC, daw3rd commented on transforms/code/higher_order_syntactic_profiler/python/pyproject.toml
> +    "data-prep-toolkit==0.2.1.dev0",
version now needs to be 0.2.2.dev0 everywhere (per the .make.versions in the current dev branch).

2024-10-04 13:30 UTC, daw3rd commented on transforms/code/higher_order_syntactic_profiler/python/pyproject.toml
> +version = "0.2.1.dev0"
version now needs to be 0.2.2.dev0 everywhere (per the .make.versions in the current dev branch).

2024-10-04 13:30 UTC, daw3rd commented on transforms/code/higher_order_syntactic_profiler/python/README.md
> +  --hosp_metrics_list HOSP_METRICS_LIST
Can you use https://github.com/IBM/data-prep-kit/blob/dev/transforms/language/pdf2parquet/python/README.md as a template for documenting the configurations and annotations.  In particular, you haven't discussed the annotations that are added, but following the format for the configuration would be good too.

2024-10-04 13:30 UTC, daw3rd commented on transforms/code/higher_order_syntactic_profiler/python/src/hosp_transform.py
> +        if self.metrics_list is not None:
You should check for this error/condition in the initializer and throw an exception there if a bad value, such as None.

2024-10-04 13:30 UTC, daw3rd commented on transforms/code/higher_order_syntactic_profiler/python/src/hosp_transform.py
> +        if self.metrics_list is not None:
It appears your are adding a column whose name is the name of the metric.  This is not clear from README.

2024-10-04 13:30 UTC, daw3rd commented on transforms/code/higher_order_syntactic_profiler/python/src/hosp_transform.py
> +        self.metrics_list = config.get("metrics", ["CCR"])
"metrics" is not what you want here I think.  Instead, use the `metrics_list` variable, defined above.

2024-10-04 13:30 UTC, daw3rd commented on transforms/code/higher_order_syntactic_profiler/python/src/output.html
This file should probably be removed

2024-10-04 13:30 UTC, daw3rd commented on transforms/code/higher_order_syntactic_profiler/ray/pyproject.toml
> +version = "0.2.1.dev0"
version number

2024-10-04 13:30 UTC, daw3rd commented on transforms/code/higher_order_syntactic_profiler/ray/pyproject.toml
> +    "dpk-hosp-transform-python==0.2.1.dev0",
version numbers

2024-10-04 13:30 UTC, daw3rd commented on transforms/code/semantic_profiler/python/README.md
> +* _sp_ikb_file_ - This is the path to the IKB file which is a CSV file and by default located in the [IKB](src/ikb/) folder.
Please follow this https://github.com/IBM/data-prep-kit/blob/dev/transforms/language/pdf2parquet/python/README.md and distinguish between transform configuration keys and cli parameters (the latter having the `sp_` prefix).

2024-10-04 13:30 UTC, daw3rd commented on transforms/code/semantic_profiler/python/README.md
> +* _sp_ikb_file_ - This is the path to the IKB file which is a CSV file and by default located in the [IKB](src/ikb/) folder.
In following the above template, please include the annotations that are added.

2024-10-04 13:30 UTC, daw3rd commented on transforms/code/semantic_profiler/python/README.md
> +| `SP_IKB_FILE`         | `ikb/ikb_model.csv`        | Path to IKB file. |
I don't hink you want caps or `SP_` here.

2024-10-04 13:30 UTC, daw3rd commented on transforms/code/semantic_profiler/python/pyproject.toml
> +version = "0.2.1.dev0"
versions

2024-10-04 13:30 UTC, daw3rd commented on transforms/code/semantic_profiler/python/pyproject.toml
> +    "data-prep-toolkit==0.2.1.dev0",
versions

2024-10-04 13:30 UTC, daw3rd commented on transforms/code/semantic_profiler/python/src/examples/examples-i.csv
DO these belong in the wheel?  If they are really examples, maybe this examples directory needs to be a sibling of the `src` directory.

2024-10-04 13:30 UTC, daw3rd commented on transforms/code/semantic_profiler/python/src/ikb/ikb_model.csv
if you really want to distribute. these, maybe they belong in a `data` directory that is a sibling of `src` and then include them in the wheel via the toml file.  My problem with this is that I'm wondering how someone would specify this file (or other data files) when using the wheel and not the repo project.  If they can be referenced from within the wheel, it would be better to specify `data/ikb/ikb_model.csv` than `src/ikb/ikb_model.csv` I think.

2024-10-04 13:30 UTC, daw3rd commented on transforms/code/semantic_profiler/ray/pyproject.toml
> +version = "0.2.1.dev0"
versions

2024-10-04 13:30 UTC, daw3rd commented on transforms/code/semantic_profiler/ray/pyproject.toml
> +    "dpk-sp-transform-python==0.2.1.dev0",
versions

2024-10-04 13:30 UTC, daw3rd commented on transforms/code/semantic_profiler/ray/test-data/expected/metadata.json
> +        "job name": "NOOP",
this file needs to be regenerated since it seems to have been copied from the NOOP project.

2024-10-04 13:41 UTC, aishwariyachakraborty commented on transforms/code/semantic_profiler/python/src/examples/examples-i.csv
No these are data files to be used by the code, same as the csv files.

2024-10-12 15:28 UTC, touma-I requested changes
@aishwariyachakraborty: Please slack me when you have change to discuss - Internal ID touma@us.ibm.com

2024-10-14 10:29 UTC, aishwariyachakraborty commented
It was suggested that we combine this with the Syntactic Construct Extractor transform into a single transform. So I am closing this PR. I will create a new PR after the PR for Syntactic Construct Extractor transform is merged with the dev branch. Hope this is ok?

2024-10-14 10:38 UTC, aishwariyachakraborty commented on transforms/code/higher_order_syntactic_profiler/python/src/hosp_transform.py
> +        self.metrics_list = config.get("metrics", ["CCR"])
done, thanks

2024-10-14 20:20 UTC, daw3rd commented on .github/workflows/test-code-semantic_profiler.yml
The merge I'm referring to is one you do locally into your fork.

2024-10-17 06:46 UTC, closed without merging