Added ray-based version of hap transform
data-prep-kit/data-prep-kit pull request #685
Opened 2024-10-08 12:09 UTC by ian-cho

## Why are these changes needed?

Added ray-based version of hap transform to enable a ray runtime

2024-10-10 01:56 UTC, touma-I requested changes

2024-10-10 01:56 UTC, touma-I commented on transforms/universal/hap/ray/pyproject.toml
> +name = "dpk_hap_transform_python"
```suggestion
name = "dpk_hap_transform_ray"
```
This may be causing most of the failure as it is conflict with the pure python module. We are working on combing both modules in a single package but for now, this should be dpk_hap_transform_ray

2024-10-10 02:40 UTC, ian-cho commented
@touma-I thanks! I merged it. One previously failed test passed

2024-10-10 16:38 UTC, touma-I commented on transforms/universal/hap/ray/Makefile
> +	$(MAKE) TRANSFORM_PYTHON_VERSION=$(HAP_PYTHON_VERSION) TOML_VERSION=$(HAP_RAY_VERSION) .transforms.set-versions
```suggestion
	$(MAKE) TRANSFORM_PYTHON_VERSION=$(HAP_PYTHON_VERSION) TOML_VERSION=$(HAP_PYTHON_VERSION) .transforms.set-versions 
```
HAP_RAY_VERSION is not defined. We should use the same version for both PYTHON and RAY

2024-10-10 16:47 UTC, touma-I commented on transforms/universal/hap/ray/Makefile
> +	$(MAKE) TRANSFORM_PYTHON_VERSION=$(HAP_PYTHON_VERSION) TOML_VERSION=$(HAP_RAY_VERSION) .transforms.set-versions
tagging @shahrokhDaijavad as he is tracking this closely. @ian-cho One more change that is needed. Please review and accept if you agree. I will do one more pass tomorrow morning.

2024-10-11 13:43 UTC, touma-I approved these changes
Thank you @ian-cho. Looks good now. All checks are passing- Meging this PR now. cc: @shahrokhDaijavad

2024-10-11 13:43 UTC, merged

2024-10-11 14:36 UTC, shahrokhDaijavad commented
Thank you, @ian-cho for doing this so quickly!