Adding a resources page
data-prep-kit/data-prep-kit pull request #696
Opened 2024-10-11 07:47 UTC by sujee

## Why are these changes needed?

Placeholder for listing growing number of resources

## Related issue number (if any).

2024-10-11 16:48 UTC, shahrokhDaijavad commented
I do like the idea of having this resource page, but I saw @Bytes-Explorer 's reservations about doing this. I discussed it with Nirmit this morning and his general direction is not to make the README page longer than what it needs to be and by not having a separate resource page for these links, the README keeps getting longer. In any case, let's discuss the pros/cons in our Tuesday meeting, before approving or not.

2024-10-11 16:51 UTC, shahrokhDaijavad requested changes
Actual changes are not needed, but I put it in "request change" mode, so it doesn't get approved accidentally, before we discuss further (see my comment).

2024-10-11 18:58 UTC, sujee commented
> I do like the idea of having this resource page, but I saw @Bytes-Explorer 's reservations about doing this. I discussed it with Nirmit this morning and his general direction is not to make the README page longer than what it needs to be and by not having a separate resource page for these links, the README keeps getting longer. In any case, let's discuss the pros/cons in our Tuesday meeting, before approving or not.

I am also in favor of compact top level README.  Let's discuss.

2024-10-14 14:29 UTC, Bytes-Explorer commented
I dont have a strong opinion here. My point is that it should be easy for the user to find the information and usually I have seen repos have this information in the top level readme. @touma-I Aanchal - pls share your suggestions too.

2024-10-15 18:11 UTC, shahrokhDaijavad approved these changes
LGTM. @touma-I, we discussed this today, and unless you have a strong opinion against it, let's merge.

2024-10-15 19:13 UTC, touma-I requested changes
@sujee Need to sync with upstream and update branch with latest before editing latest.

2024-10-15 19:13 UTC, touma-I commented on README.md
Need to first sync the fork with upstream and then update the README.md to take into account the changes that were done to the upstream file.

2024-10-16 05:31 UTC, sujee commented
> @sujee Need to sync with upstream and update branch with latest before editing latest.

done.  please check again. thx

2024-10-16 14:11 UTC, shahrokhDaijavad approved these changes
LGTM. Thanks @sujee .

2024-10-16 18:33 UTC, touma-I approved these changes

2024-10-16 18:33 UTC, merged