Html2parquet example
data-prep-kit/data-prep-kit pull request #804
Opened 2024-11-16 02:55 UTC by touma-I

## Why are these changes needed?

This PR includes a example showing how html2parquet can be used in a notebook 

## Related issue number (if any).

https://github.com/IBM/data-prep-kit/issues/788

2024-11-16 03:00 UTC, touma-I commented
@shahrokhDaijavad @sungeunan-ibm Before I forget and drop this thread, please review/edit/approve as you see fit. this is the notebook showing how to invoke the html2parquet from within a notebook that I created last week. It can be further evolved based on direct reviews. Thanks

2024-11-19 17:29 UTC, sungeunan-ibm commented on transforms/language/html2parquet/notebooks/html2parquet.ipynb
> +    "    \"input_folder\": \"input\",\n",
/path/to/your/input/folder
/path/to/your/output/folder

^to make sure it's the folder not files.

2024-11-19 17:29 UTC, sungeunan-ibm commented on transforms/language/html2parquet/notebooks/html2parquet.ipynb
> +    "    \"data_files_to_use\": ast.literal_eval(\"['.html']\"),\n",
"data_files_to_use": ast.literal_eval("['.zip', '.html']"),

support zip as well

2024-11-19 17:31 UTC, sungeunan-ibm commented on transforms/language/html2parquet/notebooks/html2parquet.ipynb
> +    "table = pq.read_table('output/ai-alliance-index.parquet')\n",
table = pq.read_table('/path/to/your/output/folder/sample.parquet')

users don't have "ai-alliance-index.parquet" so making it general.

2024-11-19 17:32 UTC, sungeunan-ibm requested changes
I left some comments.

2024-11-24 12:08 UTC, closed without merging

2024-11-24 12:08 UTC, touma-I commented
Superseded by another PR