Update README.md
data-prep-kit/data-prep-kit pull request #821
Opened 2024-11-22 06:35 UTC by ian-cho

update readme for hap transform

## Related issue number (if any).
https://github.com/IBM/data-prep-kit/issues/753

2024-11-22 15:59 UTC, shahrokhDaijavad commented
Thank you, @ian-cho. The README looks good. Three requests:
1) Can you please add a "Contributors" section with your name and email at the top like this: https://github.com/IBM/data-prep-kit/tree/update-doc_quality-readme/transforms/language/doc_quality/python? 
2) The link to the test_hap.py file seems to be broken. 
3) We have now finalized the format of the example notebook. Can you please create one like this: https://github.com/IBM/data-prep-kit/blob/update-doc_quality-readme/transforms/language/doc_quality/doc_quality.ipynb? Of course, the content will be similar to what you have in hap_local_python.py and some text from your README about the parameters. Thank you.

2024-11-22 15:59 UTC, shahrokhDaijavad requested changes
Please see my comments.

2024-11-28 10:09 UTC, ian-cho commented
@shahrokhDaijavad the links seems to be broken:

- https://github.com/IBM/data-prep-kit/tree/update-doc_quality-readme/transforms/language/doc_quality/python?
- https://github.com/IBM/data-prep-kit/blob/update-doc_quality-readme/transforms/language/doc_quality/doc_quality.ipynb

2024-11-28 23:49 UTC, shahrokhDaijavad commented
Sorry, @ian-cho. After I gave you the links to the branch above, the branch was merged, so the new links are in the dev branch at:
https://github.com/IBM/data-prep-kit/blob/dev/transforms/language/doc_quality/python/README.md
and 
https://github.com/IBM/data-prep-kit/blob/dev/transforms/language/doc_quality/doc_quality.ipynb

2024-12-02 14:07 UTC, ian-cho commented
@shahrokhDaijavad Hi, I updated the PR as requested. Please review, thanks.
1. added contributor 
2. For the link, replace it with notebook
3. added the hap python notebook.

2024-12-02 17:08 UTC, shahrokhDaijavad commented on transforms/universal/hap/python/README.md
> +[notebook](../hap_python.ipynb)
The link to the notebook is broken. The correct link is: ./hap_python.ipynb, because the notebook is in the python directory.

2024-12-02 17:33 UTC, shahrokhDaijavad reviewed
@ian-cho For the notebook, before the current cell 1 that imports the necessary packages, can you please add what we add in our template notebook, similar to what is here: https://github.com/IBM/data-prep-kit/blob/dev/transforms/language/doc_quality/doc_quality.ipynb. This is for consistency of notebooks.

2024-12-03 02:37 UTC, ian-cho commented
@shahrokhDaijavad Thank you for further suggestions. Before code cells, I added markdown content and configurations for the hap transforms just as _doc_quality.ipynb_ did. Please review.

2024-12-03 02:41 UTC, shahrokhDaijavad commented
Thank you, @ian-cho. The notebook looks good. And what about the broken link in the README above?

2024-12-03 04:59 UTC, ian-cho commented
> Thank you, @ian-cho. The notebook looks good. And what about the broken link in the README above?

Sorry, I missed that. Fixed it

2024-12-03 05:48 UTC, shahrokhDaijavad approved these changes
LGTM. Thank you, @ian-cho.

2024-12-03 23:01 UTC, merged