PII data file
data-prep-kit/data-prep-kit pull request #828
Opened 2024-11-25 14:18 UTC by PoojaHolkar

## Why are these changes needed?
This is PII data file needed to run the PII reactor notebook

## Related issue number (if any).

2024-12-03 00:21 UTC, shahrokhDaijavad commented
@touma-I This is a very different notebook than the templates we provide with the other transforms. However, it does the job of showing the effectiveness of PII in an example. It pip installs all the packages that it needs. Since it is in the "examples" folder, I wonder if we should approve it as is.

2024-12-06 00:54 UTC, touma-I commented on examples/notebooks/PII/Run_your_first_PII_redactor_transform.ipynb
@PoojaHolkar I tested the following on colab and they seem to work:
```
!pip install data-prep-toolkit==0.2.2
!pip install 'data-prep-toolkit-transforms[pii_redactor]==0.2.2'

from pii_redactor_transform import PIIRedactorTransform
```

2024-12-06 17:31 UTC, shahrokhDaijavad commented
@PoojaHolkar  Does the notebook run successfully on the local laptop? As @touma-I said in slack, neither of us could get the packages installed successfully on the local laptop while the notebook worked in the Google colab environment. If your laptop is a Mac and all the packages get installed successfully on it, we need to investigate the difference between your local environment and ours.

2024-12-08 12:29 UTC, PoojaHolkar commented
> @PoojaHolkar Does the notebook run successfully on the local laptop? As @touma-I said in slack, neither of us could get the packages installed successfully on the local laptop while the notebook worked in the Google colab environment. If your laptop is a Mac and all the packages get installed successfully on it, we need to investigate the difference between your local environment and ours.

2024-12-08 12:31 UTC, PoojaHolkar commented
@shahrokhDaijavad it is running on my local as well. am using python version 3.11.10

2024-12-08 20:01 UTC, shahrokhDaijavad commented
@PoojaHolkar Did you close the PR by accident? I reopened it and tried the latest version. It works perfectly on Google Colab. I am sending you a picture of the error I get on my local machine. It seems that the "wget" command is not found and as a result, invoice.pdf is not found. The importing of the transform (PIIRedactorTransform) is working correctly. 

I assume it is because you have wget installed on your machine, and I don't. 
<img width="716" alt="image" src="https://github.com/user-attachments/assets/6c37a8e8-38b1-446e-9c7c-f615f68c241a">

2024-12-08 20:28 UTC, shahrokhDaijavad commented
@touma-I I will approve this PR. I think all the pip installs at the top of the notebook are needed for the Google Colab and the Google Colab button will work, when this fork is merged and wget is a non-issue in the Colab environment.

2024-12-08 20:28 UTC, shahrokhDaijavad approved these changes
Please see my comments.

2024-12-09 16:59 UTC, shahrokhDaijavad commented
@touma-I Checking the requirements.txt file for the transform and what @PoojaHolkar has in the notebook:
requirements.txt:

data-prep-toolkit>=0.2.3.dev0
presidio-analyzer>=2.2.355
presidio-anonymizer>=2.2.355
flair>=0.14.0
pandas>=2.2.2

In the notebook:

!pip install data-prep-toolkit==0.2.2
!pip install 'data-prep-toolkit-transforms[all]==0.2.2'
!pip install pdfplumber 
!pip install flair 
!pip install spacy 
!pip install presidio_analyzer 
!pip install presidio_anonymizer==2.2.355

2024-12-09 19:23 UTC, touma-I commented on examples/notebooks/PII/Run_your_first_PII_redactor_transform.ipynb
@PoojaHolkar You are not be install transforms[all]. Only  transforms[pii_redactor]. Also, you should not be including the transitive dependencies for the transforms. Here is what the pip install block should look like:

%%capture logpip --no-stderr
!pip install data-prep-toolkit==0.2.2
!pip install 'data-prep-toolkit-transforms[pii_redactor]==0.2.2'
!pip install pdfplumber 
!pip install spacy

2024-12-09 19:25 UTC, touma-I requested changes
The pip install block should not have [all] and should not have the transitive dependencies presidio-analyzer, presidio-anonymizer nor flair. It should look like this:
```
%%capture logpip --no-stderr
!pip install data-prep-toolkit==0.2.2
!pip install 'data-prep-toolkit-transforms[pii_redactor]==0.2.2'
!pip install pdfplumber
!pip install spacy
111

2024-12-09 19:32 UTC, touma-I requested changes

2024-12-09 19:32 UTC, touma-I commented on examples/notebooks/PII/Run_your_first_PII_redactor_transform.ipynb
Please consider using pdf2Parquet transform (instead pdfplumber) in order to ingest the pdf document. It might be a bit more cumbersome to use in its current release but we are actually making improvements to this.

2024-12-09 19:32 UTC, touma-I commented on examples/notebooks/PII/Run_your_first_PII_redactor_transform.ipynb
You should not be using the private method _redact_pii(). Instead you should use the pdf2Parquet transform to create a parquet file and then use the transform() method to redact the content.

2024-12-12 20:39 UTC, shahrokhDaijavad commented on examples/notebooks/PII/Run_your_first_PII_redactor_transform.ipynb
> +    "  !wget -O 'input-data/Invoice.pdf' 'https://raw.githubusercontent.com/PoojaHolkar/data-prep-kit/refs/heads/dev/examples/notebooks/PII/invoicedata/Invoice.pdf'\n",
Please change .../examples/notebooks/PII/invoicedata/Invoice.pdf to .../examples/notebooks/PII/input-data/Invoice.pdf

2024-12-12 20:40 UTC, shahrokhDaijavad requested changes
@PoojaHolkar I tested the Google colab notebook, after making the change manually and it worked correctly.

2024-12-17 15:08 UTC, shahrokhDaijavad approved these changes
I approve this from functionality point of view.

2024-12-19 14:23 UTC, touma-I commented on examples/notebooks/PII/Run_your_first_PII_redactor_transform.ipynb
@PoojaHolkar why do you need if __name__ == "__main__": in step 4 ? __name__ is always true in a notebook. When doing copy/paste from the scripts, please try to adapt to the code you are copying to your use case and runtime environment. cc: @shahrokhDaijavad

2024-12-19 14:26 UTC, touma-I commented on examples/notebooks/PII/Run_your_first_PII_redactor_transform.ipynb
In step 5, I don't see the need for `redactor = PIIRedactorTransform(config)`. It do not see where it is being used. If additional configuration were needed, those should have been done before launcher.launch() in step 4.

2024-12-19 14:28 UTC, touma-I requested changes
This is better than before but still needs additional work to be correct. Please see associated comments with the notebook.

2024-12-19 16:22 UTC, PoojaHolkar commented on examples/notebooks/PII/Run_your_first_PII_redactor_transform.ipynb
am using redactor here :

 'for text in data["contents"]:
    redacted_text, detected_entities = redactor._redact_pii(text)
    redacted_texts.append(redacted_text)
    detected_entities_list.append(detected_entities)

for displaying the redacted information in the output .

Let me change calling it before launcher.launch()  as you suggested.

2024-12-19 18:37 UTC, PoojaHolkar commented
@touma-I  please verify the changes, I have pushed the needed.

2024-12-19 19:12 UTC, shahrokhDaijavad commented
@PoojaHolkar and @touma-I From a functionality point of view, I just tested the latest notebook both in my local venv and   in Google Colab and verified that the notebook runs successfully to the end in both environments.

2024-12-22 13:31 UTC, PoojaHolkar commented
@touma-I  have made the changes for pulling PII transform and not its internal functions, the developer @SowmyaLR  explained the variations needed to specify in appending the column names else the transform will fail due to the duplicity in column names. Please have a look, I reckon this will now adhere with the transform guidelines.

2024-12-26 16:30 UTC, touma-I reviewed
Please do one more pass and clean up necessary pip install. Thanks

2024-12-26 16:30 UTC, touma-I commented on examples/notebooks/PII/Run_your_first_PII_redactor_transform.ipynb
@PoojaHolkar Do you still need ?

!pip install pdfplumber
!pip install spacy

2024-12-27 04:38 UTC, PoojaHolkar commented on examples/notebooks/PII/Run_your_first_PII_redactor_transform.ipynb
corrected and pushed.

2024-12-27 16:49 UTC, touma-I approved these changes

2024-12-27 16:49 UTC, merged