Html rag 1 -- Crawl a website / process HTML / run RAG queries
data-prep-kit/data-prep-kit pull request #838
Opened 2024-11-27 20:39 UTC by sujee

## Why are these changes needed?

This examples shows how to 
- crawl a website
- process HTML files
- run RAG query on HTML file contents

## Related issue number (if any).

2024-12-04 00:16 UTC, shahrokhDaijavad approved these changes
@sujee I have now tested this example successfully by going through notebooks 1 to 4. Looks good.

2024-12-04 17:41 UTC, touma-I requested changes
Hi. Can the same thing be accomplished without having to checkin all the HTML content ?

2024-12-05 19:09 UTC, sujee commented
> Hi. Can the same thing be accomplished without having to checkin all the HTML content ?

removed HTML input files that were checked in.  @touma-I

2024-12-05 21:04 UTC, sujee commented
@touma-I please hold  off merging this until I move it to 0.2.2.  thx

2024-12-06 08:16 UTC, sujee commented
@touma-I @shahrokhDaijavad 
updated to v0.2.3-dev1
good to go

2024-12-09 17:20 UTC, shahrokhDaijavad commented
@sujee @touma-I I have now tested the latest version successfully, so from a functionality point of view, I approve this version.

2024-12-09 17:21 UTC, shahrokhDaijavad approved these changes

2024-12-09 20:25 UTC, touma-I commented on examples/notebooks/html-processing/requirements.txt
Hi @sujee, question: Did you try to use both extra in the same line?
```
data-prep-toolkit-transforms[html2parquet,web2parquet]==0.2.3.dev1
```

2024-12-09 20:27 UTC, touma-I approved these changes

2024-12-09 20:28 UTC, merged