Hap score - Example Notebook
data-prep-kit/data-prep-kit pull request #840
Opened 2024-11-29 08:47 UTC by AishaDarga

## Why are these changes needed?

## Related issue number (if any).

2024-12-03 00:06 UTC, shahrokhDaijavad commented
@ian-cho This is another variation of a Notebook that uses your hap transform. Can you please review and provide comments?

2024-12-04 01:00 UTC, ian-cho commented
@shahrokhDaijavad As long as this modification does not affect other modules in the hap/python directory or make them incompatible with each other, it is fine with me.

2024-12-04 02:30 UTC, shahrokhDaijavad commented
Thanks, @ian-cho. So, just to confirm, you are ok with the changes made in hap_config.py and hap_local_python.py files, right? Any future changes to the hap transform directory need to be reviewed again.

2024-12-04 08:10 UTC, ian-cho commented
@shahrokhDaijavad Thanks for asking. If the changes affect other modules, would you mind helping resolve them when I am not available? Previously, @touma-I and you helped a lot in ensuring module compatible with each other I remember, and it was not easy for me to ensure that.

2024-12-04 12:42 UTC, AishaDarga commented
@shahrokhDaijavad @ian-cho I've updated the notebook to ensure compatibility with Google Colab and included the installation of all necessary packages directly within the notebook. Could you please review it?
Thank you!

2024-12-04 22:22 UTC, shahrokhDaijavad commented
@AishaDarga Have you tested this notebook? I ran into errors, running both on the local machine and on the Google Colab. 

On the local machine, I get errors about hap_params not being defined. 
<img width="764" alt="image" src="https://github.com/user-attachments/assets/2acf1ce9-e08d-4d99-b470-5ff2d21453a3">
and 
<img width="763" alt="image" src="https://github.com/user-attachments/assets/7402e904-4e07-4178-969b-e562ebfd315c">

On Google Colab, I get the following error:
<img width="846" alt="image" src="https://github.com/user-attachments/assets/fe3dc222-4cf0-409d-9bfb-9548933b7f95">

2024-12-05 01:12 UTC, AishaDarga commented
@shahrokhDaijavad Yes, I've tested the notebook thoroughly on my system. I'll try to re-install and test it afresh. Thank you!

2024-12-05 16:04 UTC, shahrokhDaijavad commented
@AishaDarga I just ran your latest notebook successfully, so it works fine. However, I understand you had some discussions with @touma-I about not changing the transform code. When you make the necessary changes, I will be happy to test again.

2024-12-06 05:34 UTC, AishaDarga commented
@touma-I @shahrokhDaijavad Thank you for your feedback. I've made all necessary changes in the latest commit. This version of the code leverages the HAP transform as is, without making any changes. Could you please review it

2024-12-06 17:22 UTC, shahrokhDaijavad approved these changes
This version, which I have tested successfully, looks good to me and the directories are also clean. Thanks, @AishaDarga.

2024-12-06 19:08 UTC, touma-I requested changes
Please consider removing the parquet file from git since we can regenerate it from css. Thanks

2024-12-06 19:08 UTC, touma-I commented on examples/notebooks/hap/input-parquet/customer-feedback.parquet
Please consider removing this file from the PR since the notebook is regenerating it every time. I think the csv-parquet transformation followed by HAP annotation is very effective without the parquet file checked to git

2024-12-06 19:14 UTC, touma-I commented on examples/notebooks/hap/generate_hap_score_csv.ipynb
Please consider using the released version 0.2.2:
```
! pip install  'data-prep-toolkit[ray]==0.2.2'
! pip install  'data-prep-toolkit-transforms[all]==0.2.2'
```

2024-12-06 19:17 UTC, touma-I commented on examples/notebooks/hap/generate_hap_score_csv.ipynb
remove data-prep-connector since you are NOT using it. This line can be deleted:

~~ ! pip install data-prep-connector ~~

2024-12-06 19:28 UTC, touma-I commented on examples/notebooks/hap/generate_hap_score_csv.ipynb
You do not need this line. Those are transitive dependencies of the transform itself and could break the notebook in the future if they are changed by new releases of the ransform.

~~! pip install nltk==3.9.1 transformers==4.38.2 torch>=2.2.2,<=2.4.1 pandas==2.2.2 ~~

2024-12-06 19:41 UTC, shahrokhDaijavad commented on examples/notebooks/hap/generate_hap_score_csv.ipynb
Adding these is my fault, @touma-I! Since I could get the notebook to work only after pip installing requirements.txt, I thought they were needed, but it turns out my problem was something else! In any case, what you are saying is that these dependencies are taken care of by the pip install of the transform itself and should not be done here.

2024-12-06 21:12 UTC, AishaDarga commented
@touma-I @shahrokhDaijavad I've made all necessary changes and addressed the comments given above. I've tested the latest changes and it works fine for me. Could please review it?
<img width="683" alt="image" src="https://github.com/user-attachments/assets/49e7aee1-787b-467e-b25c-0171bb597b8c">

2024-12-06 23:35 UTC, shahrokhDaijavad approved these changes
Nice job, @AishaDarga. 
@touma-I I have tested the latest version successfully with all the changes we had asked. I recommend merging this.

2024-12-07 02:39 UTC, touma-I approved these changes

2024-12-07 02:40 UTC, merged