Notebook template for transforms to run on Google Colab
data-prep-kit/data-prep-kit pull request #851
Opened 2024-12-03 20:27 UTC by Ryan-Gordon-314159

## Why are these changes needed?
This PR contains a notebook that can serve as a guide for porting transforms over to work on Google Colab

## Related issue number (if any).
Issue #844

2024-12-03 21:14 UTC, shahrokhDaijavad approved these changes
Thanks, @Ryan-Gordon-314159. As we discussed, the open colab icon will work only when this PR is merged. Other than that, I have tested this by manually running it on Google Colab.

2024-12-03 22:17 UTC, touma-I requested changes
Please see comments. We need to make this notebook tell a story (not just copy from other notebooks)

2024-12-03 22:17 UTC, touma-I commented on examples/notebooks/pdf2parquet_colab-version.ipynb
We need to change the notebook to tell a story that would be interesting to the end user. What do you think of this?
- Step 1: Enable Collab
- Step 2: Pip install
- Step 3: Identify interesting pdf files and use web crawler to fetch them. If possible, identify pdf contant that has OCR in it
- Step 4: Configure the transform to generate MD, run the transform
- Step 5: Show output from the transform, not only the new content but any other fields that the transfrom may have produced that may be of interest based on the content
- Step 6: Repeat step 4 and 5 above but with a different configuration of the tansform for example, generating Json instead of  MD or extracting OCR, etc.

2024-12-09 17:31 UTC, shahrokhDaijavad commented on examples/notebooks/pdf2parquet_colab-version.ipynb
We want to consider getting rid of my_utils.py file, if possible.

2024-12-19 15:39 UTC, touma-I requested changes
We should not be download utils.py ?

2024-12-19 15:39 UTC, touma-I commented on examples/notebooks/pdf2parquet_colab-version.ipynb
please do not download my_utils.py. I won't be able to merge this PR with this in it.

2025-02-28 19:44 UTC, closed without merging